spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoofur?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ColourFur79112167