## logback配置
logging:
  level:
    org:
      springframework:
        security: info
server:
  port: 8002
spring:
  profiles:
    active: @env@
  application:
    name: service_chat
  resources:
    static-locations: classpath:static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/colourfur/*/mapper/xml/*Mapper.xml