server:
  port: 8003
spring:
  profiles:
    active: @env@
  application:
    name: service-oss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4GDBRMU2vK3iFyaaz81Z
      keysecret: V1qQgvPwvhtr32uRDiNnWT2uCftdWk
      bucketname: colourfur